- name: Deploy wordpress
  hosts: groupe_one
  gather_facts: true
  become: true
  
  vars:
    pip_install_packages:
      - name: docker

    pip_package: python-pip
    pip_executable: pip

  pre_tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
    - name: install epel release
      yum:
        name: epel-release
        state: installed
  roles:
    - role: 'geerlingguy.pip'
    - role: 'geerlingguy.docker'
    - role: 'geerlingguy.git'
    - role: 'role_wordpress'
